### ISSUE TITLE
TemplateFileAnalyzer paths are not configurable

### ISSUE THREAD

**Issue by jackbentley** [psalm/psalm-plugin-symfony#116]
I get the following error when trying to run a taint analysis for the first time. Looks like a path is hard coded to `baseDir/templates/` which isn't necessarily true for all projects.

```
Uncaught Twig\Error\LoaderError: The "templates" directory does not exist ("/var/www/html/templates"). in /var/www/html/vendor/twig/twig/src/Loader/FilesystemLoader.php:106
Stack trace:
#0 /var/www/html/vendor/twig/twig/src/Loader/FilesystemLoader.php(87): Twig\Loader\FilesystemLoader->addPath('templates', '__main__')
#1 /var/www/html/vendor/twig/twig/src/Loader/FilesystemLoader.php(45): Twig\Loader\FilesystemLoader->setPaths(Array)
#2 /var/www/html/vendor/psalm/plugin-symfony/src/Twig/TemplateFileAnalyzer.php(33): Twig\Loader\FilesystemLoader->__construct('templates', '/var/www/html/')
#3 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(340): Psalm\SymfonyPsalmPlugin\Twig\TemplateFileAnalyzer->analyze(NULL)
#4 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(579): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(318, '/var/www/html/j...')
#5 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(269): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#6 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(639): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false, true)
#7 /var/www/html/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www/html/', false)
#8 /var/www/html/vendor/vimeo/psalm/psalm(2): require_once('/var/www/html/v...')
#9 {main}
(Psalm 4.3.1@2feba22a005a18bf31d4c7b9bdb9252c73897476 crashed due to an uncaught Throwable)
```

**Comment by adrienlucas** [comment]
Yep you are right, the `templates` path is hard coded for now. I'll prepare an MR to make it configurable.

**Comment by adrienlucas** [comment]
Hey @jackbentley please checkout !135 and let me know if it does the thing in your context :)
