### ISSUE TITLE
Twig extensions don't work in TemplateFileAnalyzer

### ISSUE THREAD

**Issue by jackbentley** [psalm/psalm-plugin-symfony#117]
It seems like Twig extensions don't work with the basic `TemplateFileAnalyzer`. 

This code uses Symfony extensions and produces this error:

```twig
{{ render_inline(controller('my_controller')) }}
```

```
Uncaught Twig\Error\SyntaxError: Unknown "controller" function. in /var/www/html/templates/test.html.twig:1
Stack trace:
#0 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(470): Twig\ExpressionParser->getFunctionNodeClass('controller', 8)
#1 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(243): Twig\ExpressionParser->getFunctionNode('controller', 8)
#2 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(183): Twig\ExpressionParser->parsePrimaryExpression()
#3 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(78): Twig\ExpressionParser->getPrimary()
#4 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(621): Twig\ExpressionParser->parseExpression(0, false)
#5 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(469): Twig\ExpressionParser->parseArguments(true)
#6 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(243): Twig\ExpressionParser->getFunctionNode('render_inline', 8)
#7 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(183): Twig\ExpressionParser->parsePrimaryExpression()
#8 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(78): Twig\ExpressionParser->getPrimary()
#9 /var/www/html/vendor/twig/twig/src/Parser.php(166): Twig\ExpressionParser->parseExpression()
#10 /var/www/html/vendor/twig/twig/src/TokenParser/BlockTokenParser.php(47): Twig\Parser->subparse(Array, true)
#11 /var/www/html/vendor/twig/twig/src/Parser.php(209): Twig\TokenParser\BlockTokenParser->parse(Object(Twig\Token))
#12 /var/www/html/vendor/twig/twig/src/Parser.php(122): Twig\Parser->subparse(NULL, false)
#13 /var/www/html/vendor/twig/twig/src/Environment.php(735): Twig\Parser->parse(Object(Twig\TokenStream))
#14 /var/www/html/tests/psalm/TemplateFileAnalyzer.php(80): Twig\Environment->parse(Object(Twig\TokenStream))
#15 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(340): TemplateFileAnalyzer->analyze(NULL)
#16 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(579): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(318, '/var/www/html/j...')
#17 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(269): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#18 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(639): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false, true)
#19 /var/www/html/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www/html/', false)
#20 /var/www/html/vendor/vimeo/psalm/psalm(2): require_once('/var/www/html/v...')
#21 {main}
(Psalm 4.3.1@2feba22a005a18bf31d4c7b9bdb9252c73897476 crashed due to an uncaught Throwable)
```

1. Can there be a way to specify extensions or write stubs for them?
2. Would it be possible to add/stub the Symfony extensions by default?

**Comment by adrienlucas** [comment]
1. Yes, there should be way to specify loaded extensions for a given setup.
2. Also yes, the functions and filters that are introduced by the Symfony twig bridges should be registered/stubbed by default.

Furthermore, maybe the best solution would be to automatically detect the loaded extensions for a given Symfony setup, but i'm not sure of how to do that properly.

I'm not sure to have the time to MR this on my own soon (at least not this month i'm afraid).
