### ISSUE TITLE
Taint analysis fails with Psalm\Type\Atomic\TString

### ISSUE THREAD

**Issue by binarious** [psalm/psalm-plugin-symfony#133]
The following class throws the error: `Can not retrieve template name from given expression (Psalm\Type\Atomic\TString)`

```php
<?php

namespace App\Templating;

use Twig\Environment;

final class TwigTemplating implements Templating
{
    private Environment $twig;

    public function __construct(Environment $twig)
    {
        $this->twig = $twig;
    }

    /** @param array<array-key, mixed> $data */
    public function render(string $template, array $data): string
    {
        return $this->twig->render($template, $data);
    }
}
```

Stacktrace:
```
ncaught Exception: Can not retrieve template name from given expression (Psalm\Type\Atomic\TString)
Stack trace in the forked worker:
#0 /Users/myuser/projects/myapp/vendor/psalm/plugin-symfony/src/Twig/TwigUtils.php(20): Psalm\SymfonyPsalmPlugin\Twig\TwigUtils::resolveStringFromExpression(Object(Psalm\Type\Atomic\TString), Object(Psalm\Internal\Analyzer\StatementsAnalyzer))
#1 /Users/myuser/projects/myapp/vendor/psalm/plugin-symfony/src/Twig/AnalyzedTemplatesTainter.php(39): Psalm\SymfonyPsalmPlugin\Twig\TwigUtils::extractTemplateNameFromExpression(Object(PhpParser\Node\Expr\Variable), Object(Psalm\Internal\Analyzer\StatementsAnalyzer))
#2 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/EventDispatcher.php(254): Psalm\SymfonyPsalmPlugin\Twig\AnalyzedTemplatesTainter::afterMethodCallAnalysis(Object(PhpParser\Node\Expr\MethodCall), 'Twig\\Environmen...', 'Twig\\Environmen...', 'Twig\\Environmen...', Object(Psalm\Context), Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Codebase), Array, Object(Psalm\Type\Union))
#3 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php(392): Psalm\Internal\EventDispatcher->dispatchAfterMethodCallAnalysis(Object(Psalm\Plugin\EventHandler\Event\AfterMethodCallAnalysisEvent))
#4 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php(401): Psalm\Internal\Analyzer\Statements\Expression\Call\Method\ExistingAtomicMethodCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(PhpParser\Node\Identifier), Array, Object(Psalm\Codebase), Object(Psalm\Context), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject), '$this->twig', Object(Psalm\Internal\MethodIdentifier), Object(Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalysisResult))
#5 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(184): Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Codebase), Object(Psalm\Context), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject), false, '$this->twig', Object(Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalysisResult))
#6 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(148): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context))
#7 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(40): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context), false, NULL, false)
#8 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ReturnAnalyzer.php(141): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context))
#9 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(504): Psalm\Internal\Analyzer\Statements\ReturnAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Return_), Object(Psalm\Context))
#10 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(172): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Return_), Object(Psalm\Context), Object(Psalm\Context))
#11 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(421): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#12 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1639): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#13 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(387): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#14 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(213): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#15 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(340): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#16 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(193): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(73, '/Users/myuser/p...')
#17 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(406): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#18 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(269): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#19 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(635): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, true)
#20 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/myuser/p...', false)
#21 /Users/myuser/projects/myapp/vendor/vimeo/psalm/psalm(2): require_once('/Users/myuser/p...')
#22 {main} in /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:357
Stack trace:
#0 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(389): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(473): Psalm\Internal\Fork\Pool->wait()
#2 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(269): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#3 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(635): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, true)
#4 /Users/myuser/projects/myapp/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/myuser/p...', false)
#5 /Users/myuser/projects/myapp/vendor/vimeo/psalm/psalm(2): require_once('/Users/myuser/p...')
#6 {main}
(Psalm 4.4.1@9fd7a7d885b3a216cff8dec9d8c21a132f275224 crashed due to an uncaught Throwable)
```

**Comment by seferov** [comment]
@binarious thank you for the report

**Comment by adrienlucas** [comment]
Yep, throwing an expection is a bit too much here. It should go into the debug output instead.
See #148

**Comment by seferov** [comment]
@binarious thank you for reporting. It is fixed in https://github.com/psalm/psalm-plugin-symfony/pull/148. If error still continues feel free to reopen the issue.
