### ISSUE TITLE
Twig taint analysis does not support @App/ syntax

### ISSUE THREAD

**Issue by ostrolucky** [psalm/psalm-plugin-symfony#90]
So our project combines `AppBundle:DataProvider/GraduateJobs:job.xml.twig` and `@App/DataProvider/GraduateJobs/job.xml.twig` syntaxes. In a project, both works, however, looks like plugin supports former one only. Can we support both? Otherwise we get

```
Scanning files...
Analyzing files...

Uncaught RuntimeException: The template @App/DataProvider/GraduateJobs/job.xml.twig was not found. in /var/www/vendor/psalm/plugin-symfony/src/Twig/CachedTemplatesMapping.php:69
Stack trace:
#0 /var/www/vendor/psalm/plugin-symfony/src/Twig/CachedTemplatesTainter.php(58): Psalm\SymfonyPsalmPlugin\Twig\CachedTemplatesMapping::getCacheClassName('@App/DataProvid...')
#1 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Provider/MethodReturnTypeProvider.php(105): Psalm\SymfonyPsalmPlugin\Twig\CachedTemplatesTainter::getMethodReturnType(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), 'Twig\\Environmen...', 'render', Array, Object(Psalm\Context), Object(Psalm\CodeLocation), NULL, NULL, NULL)
#2 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/MethodCallReturnTypeFetcher.php(53): Psalm\Internal\Provider\MethodReturnTypeProvider->getReturnType(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), 'Twig\\Environmen...', 'render', Array, Object(Psalm\Context), Object(Psalm\CodeLocation), NULL)
#3 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php(680): Psalm\Internal\Analyzer\Statements\Expression\Call\Method\MethodCallReturnTypeFetcher::fetch(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Codebase), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context), Object(Psalm\Internal\MethodIdentifier), Object(Psalm\Internal\MethodIdentifier), Object(Psalm\Internal\MethodIdentifier), 'Twig\\Environmen...', Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject), Array, Object(Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalysisResult), Object(Psalm\Internal\Type\TemplateResult))
#4 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(168): Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Codebase), Object(Psalm\Context), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject), false, NULL, Object(Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalysisResult))
#5 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(144): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context))
#6 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(39): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context), false, NULL, false)
#7 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ReturnAnalyzer.php(135): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context))
#8 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(457): Psalm\Internal\Analyzer\Statements\ReturnAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Return_), Object(Psalm\Context))
#9 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(164): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Return_), Object(Psalm\Context), Object(Psalm\Context))
#10 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(591): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#11 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1897): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#12 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(734): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#13 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(215): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#14 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(336): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#15 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(576): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(223, '/var/www/src/Ap...')
#16 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(268): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#17 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(639): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false, true)
#18 /var/www/vendor/vimeo/psalm/src/psalm.php(677): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www/', false)
#19 /var/www/vendor/vimeo/psalm/psalm(2): require_once('/var/www/vendor...')
#20 {main}
(Psalm 3.16@d03e5ef057d6adc656c0ff7e166c50b73b4f48f3 crashed due to an uncaught Throwable)
```

cc @adrienlucas

**Comment by adrienlucas** [comment]
I pushed an update at https://github.com/psalm/psalm-plugin-symfony/pull/89
It should allow the mapper to use alternative notations.  
Please if you think of any edge cases let me know.

**Comment by seferov** [comment]
fixed with https://github.com/psalm/psalm-plugin-symfony/pull/89
